// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itmjzhlonmdtyekmxjqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bWp6aGxvbm1kdHlla214anFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzY0NDAsImV4cCI6MjA2MjExMjQ0MH0.8rdfnsratWSA5B9rF8HY_EAD1eroxIdjLEfFot3LEjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);